<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DL0110EN-SkillsNetwork/Template/module%201/images/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>


<h2>Objective</h2><ul><li> How to make a prediction using multiple samples.</li></ul> 


# Table of Contents

In this lab, we will  review how to make a prediction for Linear Regression with Multiple Output. 

<div class="alert alert-block alert-info" style="margin-top: 20px">

<li><a href="#ref2">Build Custom Modules </a></li>

<br>
<p></p>
Estimated Time Needed: <strong>15 min</strong>
</div>

<hr>


<a id="ref1"></a>

<h2 align=center>Class Linear  </h2>


In [10]:
from torch import nn
import torch

Set the random seed:


In [11]:
torch.manual_seed(1)

Set the random seed:


In [12]:
class linear_regression(nn.Module):
    def __init__(self,input_size,output_size):
        super(linear_regression,self).__init__()
        self.linear=nn.Linear(input_size,output_size)
    def forward(self,x):
        yhat=self.linear(x)
        return yhat

create a linear regression  object, as our input and output will be two we set the parameters accordingly 


In [23]:
model=linear_regression(1,10)
model(torch.tensor([1.0]))

tensor([ 1.2375,  0.5619,  1.5120, -0.2306, -0.5214, -0.1042,  1.6843,  0.6735,
        -0.0383, -0.5129], grad_fn=<AddBackward0>)

we can use the diagram to represent the model or object 


<img src = "https://ibm.box.com/shared/static/icmwnxru7nytlhnq5x486rffea9ncpk7.png" width = 600, align = "center">


we can see the parameters 


In [27]:
list(model.parameters()), list(model.named_parameters())

([Parameter containing:
  tensor([[ 0.9159],
          [-0.1850],
          [ 0.5638],
          [ 0.4330],
          [-0.6464],
          [-0.8504],
          [ 0.9599],
          [ 0.0522],
          [ 0.6855],
          [ 0.2072]], requires_grad=True),
  Parameter containing:
  tensor([ 0.3216,  0.7470,  0.9482, -0.6636,  0.1250,  0.7463,  0.7244,  0.6212,
          -0.7237, -0.7201], requires_grad=True)],
 [('linear.weight',
   Parameter containing:
   tensor([[ 0.9159],
           [-0.1850],
           [ 0.5638],
           [ 0.4330],
           [-0.6464],
           [-0.8504],
           [ 0.9599],
           [ 0.0522],
           [ 0.6855],
           [ 0.2072]], requires_grad=True)),
  ('linear.bias',
   Parameter containing:
   tensor([ 0.3216,  0.7470,  0.9482, -0.6636,  0.1250,  0.7463,  0.7244,  0.6212,
           -0.7237, -0.7201], requires_grad=True))])

we can create a tensor with two rows representing one sample of data


In [15]:
x=torch.tensor([[1.0]])

we can make a prediction 


In [16]:
yhat=model(x)
yhat

tensor([[ 0.7926, -0.3920,  0.1714,  0.0797, -1.0143,  0.5097, -0.0608,  0.5047,
          1.0132,  0.1887]], grad_fn=<AddmmBackward>)

each row in the following tensor represents a different sample 


In [17]:
X=torch.tensor([[1.0],[1.0],[3.0]])

we can make a prediction using multiple samples 


In [18]:
Yhat=model(X)
Yhat

tensor([[ 0.7926, -0.3920,  0.1714,  0.0797, -1.0143,  0.5097, -0.0608,  0.5047,
          1.0132,  0.1887],
        [ 0.7926, -0.3920,  0.1714,  0.0797, -1.0143,  0.5097, -0.0608,  0.5047,
          1.0132,  0.1887],
        [ 1.8232, -1.2748, -0.2164,  1.0184, -2.8972,  1.7091, -0.4722,  1.5222,
          1.2912, -0.0561]], grad_fn=<AddmmBackward>)

the following figure represents the operation, where the red and blue  represents the different parameters, and the different shades of green represent  different samples.


 <img src = "https://ibm.box.com/shared/static/768cul6pj8hc93uh9ujpajihnp8xdukx.png" width = 600, align = "center">
